function [scenario, egoVehicle] = Prova()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 08-Jun-2022 15:40:51

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0 0 0;
    1500 0 0];
road(scenario, roadCenters, 'Name', 'Road');

roadCenters = [215 -80 0;
    215 80 0];
road(scenario, roadCenters, 'Name', 'Road1');

roadCenters = [500 200 0;
    500 -200 0];
road(scenario, roadCenters, 'Name', 'Road2');

roadCenters = [850 200 0;
    850 -148.2 0;
    850 -200 0];
headings = [-90;-90;-90];
road(scenario, roadCenters, 'Heading', headings, 'Name', 'Road3');

roadCenters = [1019.8 150 0;
    1019.8 -150 0];
road(scenario, roadCenters, 'Name', 'Road4');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [9 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [9 0 0;
    363.1 0 0;
    778.4 0 0;
    995.2 0 0;
    1209.5 0 0];
speed = [30;30;30;30;30];
waittime = [0;0;0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

% Add the non-ego actors
car1 = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [57.3 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car1');
waypoints = [57.3 0 0;
    127.3 0 0;
    181.9 0 0;
    209.8 0 0;
    213 0.3 0;
    215 -1.1 0;
    215 -3.9 0;
    215 -5.9 0;
    215 -9.3 0;
    215 -19.2 0;
    215 -63.7 0];
speed = [15;15;15;15;15;15;15;15;15;15;15];
yaw =  [0;0;0;0;0;NaN;NaN;NaN;NaN;NaN;-90.3193];
trajectory(car1, waypoints, speed, 'Yaw', yaw);

truck = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [500 195 0], ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'Truck');
waypoints = [500 195 0;
    500 0.1 0;
    500 -170 0];
speed = [30;0;30];
waittime = [0;30;0];
trajectory(truck, waypoints, speed, waittime);

pedestrian = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [616 -3.3 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian');
waypoints = [616 -3.3 0;
    616 6.8 0];
speed = [0.1;0.1];
waittime = [0;0];
trajectory(pedestrian, waypoints, speed, waittime);

pedestrian1 = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [616 -4 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian1');
waypoints = [616 -4 0;
    616 6.24 0];
speed = [0.1;0.1];
waittime = [0;0];
trajectory(pedestrian1, waypoints, speed, waittime);

pedestrian2 = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [617 -3 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian2');
waypoints = [617 -3 0;
    617 6 0];
speed = [0.1;0.1];
waittime = [0;0];
trajectory(pedestrian2, waypoints, speed, waittime);

pedestrian3 = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [615 -3 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian3');
waypoints = [615 -3 0;
    615 6 0];
speed = [0.1;0.1];
waittime = [0;0];
trajectory(pedestrian3, waypoints, speed, waittime);

bicycle = actor(scenario, ...
    'ClassID', 3, ...
    'Length', 1.7, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [850 -194.1 0], ...
    'Mesh', driving.scenario.bicycleMesh, ...
    'Name', 'Bicycle');
waypoints = [850 -194.1 0;
    850 -148 0;
    850 -113 0;
    850 -89 0;
    850 -56 0;
    850 -41 0;
    850 -21 0;
    850 -15 0;
    850 -9 0;
    850 -4 0;
    850 -2 0;
    850 0 0;
    855.3 0 0;
    868.3 0 0;
    873.9 0 0;
    891.2 0 0;
    914.4 0 0;
    1009.7 0 0;
    1017.3 0 0;
    1020 0 0;
    1020 4.3 0;
    1020 9 0;
    1020 18.5 0;
    1020 28.9 0;
    1020 39.6 0;
    1020 110.6 0];
speed = [3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3;3];
yaw =  [90;90;90;90;90;90;90;90;90;90;90;0;0;0;0;0;0;0;0;0;90;NaN;NaN;NaN;NaN;NaN];
trajectory(bicycle, waypoints, speed, 'Yaw', yaw);

